### ISSUE TITLE
[BUG] On small heights addModule creates to scrollbars (only when importing multiple files)

### ISSUE THREAD

**Issue by Rllyyy** [Rllyyy/repeatio#157]
![image](https://user-images.githubusercontent.com/57847380/183712276-a32bb3e5-ee40-4bb4-b6f4-8dec2cdaa104.png)

**Comment by Rllyyy** [comment]
The reason for it is this line of code:

```css

.import-create-module {
  overflow-y: auto;
}

````

Sadly removing it causes the padding at the bottom to be ignored:
![image](https://user-images.githubusercontent.com/57847380/183713284-699f265b-458c-4684-b498-942054336c99.png)
