### ISSUE TITLE
[BUG] KaTeX font size too big

### ISSUE THREAD

**Issue by Rllyyy** [Rllyyy/repeatio#164]
Reason:

```css
p,
span,
li,
label,
input {
  font-size: 18px;
}
```

Fix:
```css
p,
span:not(.math *):not(.math),
li,
label,
input {
  font-size: 18px;
}
```
